import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#e1bfb5",
        secondary: "#5d5c74",
        surface: "#fcf8ff",
        "tertiary-container": "#9a9996",
        "on-primary-fixed": "#390c00",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#ffb59d",
        tertiary: "#5e5e5c",
        error: "#ba1a1a",
        "on-tertiary-fixed-variant": "#474744",
        "primary-fixed": "#ffdbd0",
        "on-background": "#181934",
        "inverse-surface": "#2d2e4a",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#e4e2de",
        "on-surface": "#181934",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f2efff",
        "secondary-fixed-dim": "#c6c4df",
        "surface-bright": "#fcf8ff",
        "secondary-container": "#e2e0fc",
        "tertiary-fixed-dim": "#c8c6c3",
        "on-secondary-container": "#63627a",
        "surface-container": "#efecff",
        "on-surface-variant": "#594139",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#45455b",
        "surface-container-low": "#f5f2ff",
        "on-primary-container": "#5f1900",
        primary: "#ab3500",
        "surface-container-high": "#e8e6ff",
        "on-tertiary-container": "#31312f",
        outline: "#8d7168",
        "secondary-fixed": "#e2e0fc",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#1b1c1a",
        "primary-fixed-dim": "#ffb59d",
        "primary-container": "#ff6b35",
        "on-primary-fixed-variant": "#832600",
        "surface-container-highest": "#e2dfff",
        "surface-dim": "#d8d7fb",
        "on-error-container": "#93000a",
        "surface-variant": "#e2dfff",
        background: "#fcf8ff",
        "surface-tint": "#ab3500",
        "on-secondary-fixed": "#1a1a2e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        card: "16px",
      },
      spacing: {
        gutter: "24px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "section-padding-mobile": "48px",
        "section-padding": "80px",
        "max-container": "1200px",
        "stack-md": "16px",
      },
      fontFamily: {
        "body-md": ["var(--font-plus-jakarta)", "system-ui", "sans-serif"],
        "label-sm": ["var(--font-plus-jakarta)", "system-ui", "sans-serif"],
        "display-lg": ["var(--font-noto-serif)", "Georgia", "serif"],
        "label-md": ["var(--font-plus-jakarta)", "system-ui", "sans-serif"],
        "display-lg-mobile": ["var(--font-noto-serif)", "Georgia", "serif"],
        "headline-sm": ["var(--font-noto-serif)", "Georgia", "serif"],
        "headline-md": ["var(--font-noto-serif)", "Georgia", "serif"],
        "body-lg": ["var(--font-plus-jakarta)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "display-lg": [
          "48px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      boxShadow: {
        ambient: "0 2px 16px rgba(0,0,0,0.07)",
        "ambient-hover": "0 4px 24px rgba(0,0,0,0.12)",
        card: "0 2px 16px rgba(0,0,0,0.07)",
        "card-hover": "0 4px 24px rgba(0,0,0,0.1)",
      },
      maxWidth: {
        "max-container": "1200px",
      },
    },
  },
  plugins: [],
};

export default config;
